#!/system/bin/sh
busybox mount -o rw,remount /system;

MTD=`ls -d /sys/block/mtd*`;
LOOP=`ls -d /sys/block/loop*`;
RAM=`ls -d /sys/block/ram*`;
MMC=`ls -d /sys/block/mmc*`;
for j in $MMC $MTD $LOOP $RAM;
do
busybox echo "0" > $j/queue/rotational;
busybox echo "2048" > $j/queue/read_ahead_kb;. 
done;

# Set SD Card Cache
busybox echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb

# etc
busybox echo "0" > /proc/sys/net/ipv6/conf/all/forwarding
busybox echo "0" > /proc/sys/net/ipv4/tcp_timestamps
busybox echo "1" > /proc/sys/net/ipv4/tcp_no_metrics_save
busybox echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
busybox echo "1" > /proc/sys/net/ipv4/tcp_sack;
busybox echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
busybox echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
busybox echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
busybox echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;

# Memory Thresholds
FOREGROUND_APP_MEM=2048
VISIBLE_APP_MEM=3072
PERCEPTIBLE_APP_MEM=4096
HEAVY_WEIGHT_APP_MEM=6144
SECONDARY_SERVER_MEM=7168
BACKUP_APP_MEM=7168
HOME_APP_MEM=4096
HIDDEN_APP_MEM=10240
EMPTY_APP_MEM=12288

# Apply MEM limits
busybox echo $FOREGROUND_APP_MEM,$VISIBLE_APP_MEM,$PERCEPTIBLE_APP_MEM,$SECONDARY_SERVER_MEM,$HIDDEN_APP_MEM,$EMPTY_APP_MEM > /sys/module/lowmemorykiller/parameters/minfree

setprop ro.FOREGROUND_APP_MEM $FOREGROUND_APP_MEM
setprop ro.VISIBLE_APP_MEM $VISIBLE_APP_MEM
setprop ro.HEAVY_WEIGHT_APP_MEM $HEAVY_WEIGHT_APP_MEM
setprop ro.HOME_APP_MEM $HOME_APP_MEM

# drop garbage in caches
rm -f /cache/*.apk;
rm -f /cache/*.tmp;
rm -f /data/dalvik-cache/*.apk;
rm -f /data/dalvik-cache/*.tmp;
rm -f /data/system/dropbox/*;

# Enable Sysctl Tweaks
sysctl -w vm.dirty_background_ratio=35
sysctl -w vm.dirty_ratio=70
sysctl -w vm.panic_on_oom=0
sysctl -w vm.laptop_mode=0
sysctl -w vm.dirty_writeback_centisecs=400
sysctl -w vm.page-cluster=3
sysctl -w vm.overcommit_memory=0
sysctl -w vm.block_dump=0
sysctl -w vm.oom_dump_tasks=0
sysctl -w vm.oom_kill_allocating_task=1
sysctl -w vm.swappiness=40
sysctl -w vm.min_free_kbytes=8192
sysctl -w vm.min_free_order_shift=4

# File System Tweaks & Cleanup
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier =0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /data
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /cache
busybox mount -o remount,noatime,nodiratime,discard,noauto_da_alloc,nodev /sys

# Breaking the lease
sysctl -w fs.lease-break-time=10

busybox mount -o ro,remount /system;
