#!/system/xbin/sh
# Vanir Mods

#
# File System Tweaks & Cleanup
#
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier=0,nobh,data=writeback /system
for m in "/data" "/cache"; do
  busybox mount -o remount,commit=19,barrier=0,discard,nomblk_io_submit,noauto_da_alloc,nobh,nouser_xattr,errors=continue,noatime,nodiratime,nosuid,nodev,data=writeback $m
done
