# Gapps
PRODUCT_COPY_FILES += \
    vendor/mirage/prebuilt/common/app/CalendarGoogle.apk:system/app/CalendarGoogle.apk \
    vendor/mirage/prebuilt/common/app/ChromeBookmarksSyncAdapter.apk:system/app/ChromeBookmarksSyncAdapter.apk \
    vendor/mirage/prebuilt/common/app/Gmail.apk:system/app/Gmail.apk \
    vendor/mirage/prebuilt/common/app/GmsCore.apk:system/app/GmsCore.apk \
    vendor/mirage/prebuilt/common/app/GoogleBackupTransport.apk:system/app/GoogleBackupTransport.apk \
    vendor/mirage/prebuilt/common/app/GoogleCalendarSyncAdapter.apk:system/app/GoogleCalendarSyncAdapter.apk \
    vendor/mirage/prebuilt/common/app/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter.apk \
    vendor/mirage/prebuilt/common/app/GoogleFeedback.apk:system/app/GoogleFeedback.apk \
    vendor/mirage/prebuilt/common/app/GoogleLoginService.apk:system/app/GoogleLoginService.apk \
    vendor/mirage/prebuilt/common/app/GooglePartnerSetup.apk:system/app/GooglePartnerSetup.apk \
    vendor/mirage/prebuilt/common/app/GoogleServicesFramework.apk:system/app/GoogleServicesFramework.apk \
    vendor/mirage/prebuilt/common/app/LatinImeDictionaryPack.apk:system/app/LatinImeDictionaryPack.apk \
    vendor/mirage/prebuilt/common/app/MediaUploader.apk:system/app/MediaUploader.apk \
    vendor/mirage/prebuilt/common/app/NetworkLocation.apk:system/app/NetworkLocation.apk \
    vendor/mirage/prebuilt/common/app/OneTimeInitializer.apk:system/app/OneTimeInitializer.apk \
    vendor/mirage/prebuilt/common/app/SetupWizard.apk:system/app/SetupWizard.apk \
    vendor/mirage/prebuilt/common/app/SpareParts.apk:system/app/SpareParts.apk \
    vendor/mirage/prebuilt/common/app/Talk.apk:system/app/Talk.apk \
    vendor/mirage/prebuilt/common/app/Vending.apk:system/app/Vending.apk \
    vendor/mirage/prebuilt/common/app/YouTube.apk:system/app/YouTube.apk \
    vendor/mirage/prebuilt/common/app/VisualizationWallpapers.apk:system/app/VisualizationWallpapers.apk \
    vendor/mirage/prebuilt/common/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/mirage/prebuilt/common/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/mirage/prebuilt/common/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/mirage/prebuilt/common/etc/permissions/features.xml:system/etc/permissions/features.xml \
    vendor/mirage/prebuilt/common/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/mirage/prebuilt/common/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/mirage/prebuilt/common/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    vendor/mirage/prebuilt/common/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/mirage/prebuilt/common/lib/libgtalk_jni.so:system/lib/libgtalk_jni.so \
    vendor/mirage/prebuilt/common/lib/libgtalk_stabilize.so:system/lib/libgtalk_stabilize.so \
    vendor/mirage/prebuilt/common/lib/libjni_latinimegoogle.so:system/lib/libjni_latinimegoogle.so \
    vendor/mirage/prebuilt/common/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    vendor/mirage/prebuilt/common/lib/libvorbisencoder.so:system/lib/libvorbisencoder.so
